# Generated by Django 3.2.8 on 2021-10-12 03:02

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='', upload_to=posts.models.Post.upload_to),
        ),
    ]
